version: '3.8'

services:
  backend:
    build: .
    container_name: gamehub-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - gamehub-network
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "eu-north-1"
        awslogs-group: "My-GameHub-Log-Group"
        awslogs-stream: "backend"

  redis:
    image: redis:7-alpine
    container_name: gamehub-redis
    restart: always
    # Redis is NOT exposed to the host/public, only to the 'backend' service
    networks:
      - gamehub-network
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

networks:
  gamehub-network:
    driver: bridge

volumes:
  redis_data:
