name: Build and Publish images to DockerHub

on:
  workflow_dispatch:

jobs:
  publish_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker build -t ahmedadelabouhussein/web_app_backend:latest ./backend
          docker push ahmedadelabouhussein/web_app_backend:latest

  publish_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Image
        run: |
          docker build \
            --build-arg VITE_REACT_APP_BACKEND_URL=${{ secrets.VITE_REACT_APP_BACKEND_URL }} \
            -t ahmedadelabouhussein/web_app_frontend:latest \
            ./frontend
          docker push ahmedadelabouhussein/web_app_frontend:latest
